apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hello-gitops
  namespace: hello-gitops
spec:
  rules:
  - host: test.apps.example.info
    http:
      paths:
      - backend:
          serviceName: hello-gitops
          servicePort: http
              
            
              
