apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
- ngnix.yaml
- controller.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: hariprasad326/hello-gitops
  newTag: 180a66ceab04dac97d94810a5ebb4e6546e619db
