apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-gitops
images:
- name: hello-gitops
  newName: hariprasad326/hello-gitops
  newTag: 744db575e7e648f1239aee86926ee8985fc0d818
